#!/usr/bin/env bash

if
  [[ -s "/Users/ishan/.rvm/gems/ruby-2.2.2/environment" ]]
then
  source "/Users/ishan/.rvm/gems/ruby-2.2.2/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/ishan/.rvm/gems/ruby-2.2.2/environment'" >&2
  exit 1
fi
