#!/usr/bin/env bash

if
  [[ -s "/Users/ishan/.rvm/gems/ruby-2.2.2@global/environment" ]]
then
  source "/Users/ishan/.rvm/gems/ruby-2.2.2@global/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/ishan/.rvm/gems/ruby-2.2.2@global/environment'" >&2
  exit 1
fi
